Algoritmo "Exercicio 5"

Var
nome_aluno: caractere
n1,n2,n3,media: real


Inicio
Escreval("Digite o nome do aluno")
Leia (nome_aluno)

Escreval("Digite a primeira nota do semestre")
Leia (n1)

Escreval("Digite a segunda nota do semestre")
Leia (n2)

Escreval("Digite a terceira nota do semestre")
Leia (n3)

media<-(n1+n2+n3)/3
Escreval ("O aluno ", nome_aluno," obteve em sua média no semestre, a nota ", media)

Fimalgoritmo